/**
 * The HAALVING mark set — 77 hairline marks, ported VERBATIM from the ICONS
 * map in demo/app/js/core.js.
 *
 * One voice: a 24-box, stroke 1.6 (set in CSS, not here), round caps. These
 * replace every pictorial emoji in the product — there are no emoji anywhere in
 * HAALVING, and adding one would break the drawing language rather than merely
 * looking out of place.
 *
 * The path data is lifted rather than retraced: 68 marks is 68 chances to be a
 * pixel out, and the marks are the product's handwriting.
 *
 * Generated by scratchpad/extract-icons.mjs. Edit the demo, re-run, review.
 */
import type { SVGProps } from 'react';

export const ICON_PATHS = {
  home: (
    <><path d="M3 11.5 12 4l9 7.5M5.5 10v9h13v-9"/></>
  ),
  cal: (
    <><rect x="4" y="6" width="16" height="14" rx="2"/><path d="M4 10h16M8 4v4M16 4v4"/></>
  ),
  chat: (
    <><path d="M4 6h16v10H9l-5 4z"/></>
  ),
  circle: (
    <><circle cx="12" cy="12" r="8"/><path d="M8.5 10.5h7M8.5 14h4.5"/></>
  ),
  chart: (
    <><path d="M4 20V9M10 20V4M16 20v-8M21 20H3"/></>
  ),
  user: (
    <><circle cx="12" cy="8" r="3.5"/><path d="M5 20c1.3-3.5 4-5 7-5s5.7 1.5 7 5"/></>
  ),
  users: (
    <><circle cx="9" cy="8.5" r="3"/><path d="M3.5 19c1-2.8 3.1-4.2 5.5-4.2s4.5 1.4 5.5 4.2M15.5 6a2.8 2.8 0 1 1 0 5.6M17 14.9c2 .4 3.4 1.7 4 4.1"/></>
  ),
  tribe: (
    <><circle cx="12" cy="6.5" r="2.6"/><circle cx="5.2" cy="9.5" r="2.1"/><circle cx="18.8" cy="9.5" r="2.1"/><path d="M8.4 20c.6-3.1 2-4.7 3.6-4.7s3 1.6 3.6 4.7M2.3 18.3c.5-2.3 1.6-3.6 3.1-3.9M21.7 18.3c-.5-2.3-1.6-3.6-3.1-3.9"/></>
  ),
  zone: (
    <><rect x="3.6" y="8.2" width="12.2" height="12.2" rx="2.6"/><path d="M8.2 6.2a2.6 2.6 0 0 1 2.6-2.6h7a2.6 2.6 0 0 1 2.6 2.6v7a2.6 2.6 0 0 1-2.6 2.6"/><path d="M6.4 17c1.2-2.6 2.5-3.9 3.9-3.9 1.1 0 1.9.8 2.4 2.3"/></>
  ),
  bulb: (
    <><path d="M9.5 18h5M10.5 21h3M12 3.5a5.5 5.5 0 0 1 3 10.1c-.7.5-1 1.3-1 2.4h-4c0-1.1-.3-1.9-1-2.4a5.5 5.5 0 0 1 3-10.1z"/></>
  ),
  bookmark: (
    <><path d="M7 4h10v16l-5-3.5L7 20z"/></>
  ),
  more: (
    <><circle cx="5.5" cy="12" r=".9"/><circle cx="12" cy="12" r=".9"/><circle cx="18.5" cy="12" r=".9"/></>
  ),
  camera: (
    <><path d="M4 8h3l2-2.5h6L17 8h3v11H4z"/><circle cx="12" cy="13" r="3.4"/></>
  ),
  grid: (
    <><rect x="4" y="4" width="7" height="7" rx="1.5"/><rect x="13" y="4" width="7" height="7" rx="1.5"/><rect x="4" y="13" width="7" height="7" rx="1.5"/><rect x="13" y="13" width="7" height="7" rx="1.5"/></>
  ),
  heart: (
    <><path d="M12 20s-7-4.6-7-10a4 4 0 0 1 7-2.6A4 4 0 0 1 19 10c0 5.4-7 10-7 10z"/></>
  ),
  flow: (
    <><circle cx="6" cy="6" r="2.5"/><circle cx="18" cy="12" r="2.5"/><circle cx="6" cy="18" r="2.5"/><path d="M8.5 6H14a2 2 0 0 1 2 2v1.5M8.5 18H14a2 2 0 0 0 2-2v-1.5"/></>
  ),
  check: (
    <><path d="M4 12.5 9.5 18 20 6.5"/></>
  ),
  gear: (
    <><circle cx="12" cy="12" r="3"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/></>
  ),
  menu: (
    <><path d="M4 7h16M4 12h16M4 17h16"/></>
  ),
  mic: (
    <><rect x="9.5" y="4" width="5" height="10" rx="2.5"/><path d="M6 12a6 6 0 0 0 12 0M12 18v3"/></>
  ),
  phone: (
    <><path d="M5 4.5C5 3.7 5.7 3 6.5 3h2L10 7.5 8 9.3a13.5 13.5 0 0 0 6.7 6.7l1.8-2L21 15.5v2c0 .8-.7 1.5-1.5 1.5C10.8 19 5 13.2 5 4.5z"/></>
  ),
  device: (
    <><rect x="7.5" y="3.5" width="9" height="17" rx="2.4"/><path d="M10.5 17.5h3"/></>
  ),
  video: (
    <><rect x="3.5" y="7" width="12" height="10" rx="2"/><path d="M15.5 11l5-2.5v7l-5-2.5"/></>
  ),
  sound: (
    <><path d="M4 9.5h3.5L12 5.5v13L7.5 14.5H4z"/><path d="M15.5 9.2a4 4 0 0 1 0 5.6M18.2 6.6a7.6 7.6 0 0 1 0 10.8"/></>
  ),
  drop: (
    <><path d="M12 4.5c2.9 3.3 5 6.1 5 8.8a5 5 0 0 1-10 0c0-2.7 2.1-5.5 5-8.8z"/></>
  ),
  moon: (
    <><path d="M19 14.5A7.5 7.5 0 0 1 9.5 5 7.5 7.5 0 1 0 19 14.5z"/></>
  ),
  bowl: (
    <><path d="M4.5 12.5h15a7.5 7.5 0 0 1-5 6.3v1.2h-5v-1.2a7.5 7.5 0 0 1-5-6.3z"/><path d="M10 9.5c0-1.2 1-1.6 1-2.8M14 9.5c0-1.2 1-1.6 1-2.8"/></>
  ),
  leaf: (
    <><path d="M6 18C6 10 11 5.5 19 5c.5 8-4 13-13 13z"/><path d="M6 18c2.5-5 6-8.5 10-10.5"/></>
  ),
  sprout: (
    <><path d="M12 20.5v-7"/><path d="M12 13.5C12 10 9.5 7.5 6 7.5c0 3.5 2.5 6 6 6z"/><path d="M12 11.5c0-3 2-5.5 6-5.5 0 3-2 5.5-6 5.5z"/></>
  ),
  lock: (
    <><rect x="5.5" y="10.5" width="13" height="9" rx="2"/><path d="M8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5"/></>
  ),
  sparkle: (
    <><path d="M12 4l1.8 5.2L19 11l-5.2 1.8L12 18l-1.8-5.2L5 11l5.2-1.8z"/></>
  ),
  bell: (
    <><path d="M6 16v-5a6 6 0 0 1 12 0v5l1.5 2.5h-15z"/><path d="M10 21a2.2 2.2 0 0 0 4 0"/></>
  ),
  award: (
    <><circle cx="12" cy="9" r="5"/><path d="M9.2 13.3 7.5 20l4.5-2.5L16.5 20l-1.7-6.7"/></>
  ),
  ruler: (
    <><rect x="9" y="3" width="6" height="18" rx="1.5"/><path d="M9 7.5h3M9 12h3M9 16.5h3"/></>
  ),
  gauge: (
    <><path d="M5 17a8 8 0 1 1 14 0"/><path d="M12 13.5 15.5 10"/><circle cx="12" cy="14.5" r="1.2"/></>
  ),
  target: (
    <><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4.5"/><circle cx="12" cy="12" r="1.2"/></>
  ),
  doc: (
    <><path d="M7 3.5h7l4 4V20.5H7z"/><path d="M14 3.5V8h4M10 12.5h5M10 16h5"/></>
  ),
  clock: (
    <><circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/></>
  ),
  sun: (
    <><circle cx="12" cy="12" r="4"/><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/></>
  ),
  walk: (
    <><circle cx="13.5" cy="4.5" r="1.7"/><path d="M13 7.5 10.5 12l3 3 1 5.5M10.5 12 8 14l-1.5 5.5M13 7.5l3 2 2.5 1"/></>
  ),
  play: (
    <><path d="M8.5 5.5 18 12l-9.5 6.5z"/></>
  ),
  pause: (
    <><path d="M9 5.5v13M15 5.5v13"/></>
  ),
  plus: (
    <><path d="M12 5v14M5 12h14"/></>
  ),
  plusbox: (
    <><rect x="4" y="4" width="16" height="16" rx="3.6"/><path d="M12 8.6v6.8M8.6 12h6.8"/></>
  ),
  minus: (
    <><path d="M5 12h14"/></>
  ),
  arrow: (
    <><path d="M5 12h14M13 6l6 6-6 6"/></>
  ),
  chevL: (
    <><path d="M14.5 5 8 12l6.5 7"/></>
  ),
  chevR: (
    <><path d="M9.5 5 16 12l-6.5 7"/></>
  ),
  info: (
    <><circle cx="12" cy="12" r="8.5"/><path d="M12 11v5M12 7.8v.1"/></>
  ),
  scale: (
    <><rect x="4" y="4" width="16" height="16" rx="3"/><path d="M8.3 10.5a4.5 4.5 0 0 1 7.4 0M12 12.5l1.8-2"/></>
  ),
  flag: (
    <><path d="M6 21V4"/><path d="M6 5h11l-2.5 3.5L17 12H6"/></>
  ),
  shield: (
    <><path d="M12 3.5 19 6v5.5c0 4.5-3 7.7-7 9-4-1.3-7-4.5-7-9V6z"/></>
  ),
  flame: (
    <><path d="M12 3.5c.8 3.2-4.5 5.3-4.5 10a4.5 4.5 0 0 0 9 .2c0-2.2-1.2-3.6-2-4.7-.9 1-1.4 2-1.2 3.2-1.5-1.6-1.8-5.2-1.3-8.7z"/></>
  ),
  pencil: (
    <><path d="M4 20l1-4L16.5 4.5a2.12 2.12 0 0 1 3 3L8 19z"/><path d="M14.5 6.5l3 3"/></>
  ),
  search: (
    <><circle cx="11" cy="11" r="6.5"/><path d="M15.7 15.7 20 20"/></>
  ),
  send: (
    <><path d="M4 11.5 20 4l-4.5 16-3.5-6.5z"/><path d="M12 13.5 20 4"/></>
  ),
  x: (
    <><path d="M6 6l12 12M18 6 6 18"/></>
  ),
  warn: (
    <><path d="M12 4 21 19.5H3z"/><path d="M12 10v4M12 16.6v.1"/></>
  ),
  smile: (
    <><circle cx="12" cy="12" r="8.5"/><path d="M8.4 14.1a4.3 4.3 0 0 0 7.2 0"/><path d="M9.2 9.5v.1M14.8 9.5v.1"/></>
  ),
  clip: (
    <><path d="M17.5 11.3 11.6 17a3.7 3.7 0 1 1-5.2-5.2l7-7a2.4 2.4 0 0 1 3.4 3.4l-6.9 7a1.2 1.2 0 0 1-1.7-1.7l5.9-5.9"/></>
  ),
  scan: (
    <><path d="M4 8.6V6.2A2.2 2.2 0 0 1 6.2 4h2.4M15.4 4h2.4A2.2 2.2 0 0 1 20 6.2v2.4M20 15.4v2.4a2.2 2.2 0 0 1-2.2 2.2h-2.4M8.6 20H6.2A2.2 2.2 0 0 1 4 17.8v-2.4"/><path d="M8.2 11.4h7.6a3.8 3.8 0 0 1-7.6 0z"/></>
  ),
  star: (
    <><path d="M12 3.6l2.6 5.75 6.25.72-4.65 4.2 1.25 6.18L12 17.3l-5.45 3.15 1.25-6.18-4.65-4.2 6.25-.72z"/></>
  ),
  caretUp: (
    <><path d="M6.5 14.5 12 9l5.5 5.5"/></>
  ),
  caretDown: (
    <><path d="M6.5 9.5 12 15l5.5-5.5"/></>
  ),
  pulse: (
    <><path d="M3 12.5h4.2l2.3-5.5 3.6 10 2.4-6.5 1.3 2h4.2"/></>
  ),
  dumbbell: (
    <><path d="M7 8.5v7M4.2 10v4M17 8.5v7M19.8 10v4M7 12h10"/></>
  ),
  cutlery: (
    <><path d="M7 3.8v4a2.3 2.3 0 0 0 4.6 0v-4M9.3 3.8v16.4"/><ellipse cx="16.2" cy="6.8" rx="2.1" ry="3"/><path d="M16.2 9.8v10.4"/></>
  ),
  meditate: (
    <><circle cx="12" cy="5.6" r="2.1"/><path d="M9.9 9.2C8.1 10 7 11.6 6.4 13.9M14.1 9.2c1.8.8 2.9 2.4 3.5 4.7M4.6 17.6c2.2-2.3 4.7-3.4 7.4-3.4s5.2 1.1 7.4 3.4"/></>
  ),
  molecule: (
    <><circle cx="12" cy="5.6" r="2.3"/><circle cx="5.8" cy="16.4" r="2.3"/><circle cx="18.2" cy="16.4" r="2.3"/><path d="M10.8 7.6 7 14.4M13.2 7.6 17 14.4M8.1 16.4h7.8"/></>
  ),
  microbe: (
    <><path d="M12 4.2c3.5 0 6.3 2.7 6.3 6.1 0 4.1-2.5 9.5-6.3 9.5s-6.3-5.4-6.3-9.5c0-3.4 2.8-6.1 6.3-6.1z"/><circle cx="10.1" cy="10.4" r="1.1"/><circle cx="14" cy="13.2" r="1.1"/></>
  ),
  kidney: (
    <><path d="M14.6 4c3 0 5.4 3.6 5.4 8s-2.4 8-5.4 8c-2.2 0-3.5-1.7-4.4-3.3-1.2-2-3.2-2.8-4.8-3.6-1.1-.6-1.4-1-1.4-1.4s.3-.8 1.4-1.4c1.6-.8 3.6-1.6 4.8-3.6C11.1 5.7 12.4 4 14.6 4z"/><path d="M14.4 8.4 11.6 12h3.5"/></>
  ),
  liver: (
    <><path d="M3.6 9.4c4.2-2.6 11.3-3.5 17-1.4-.4 5.6-3.4 9.7-8.1 10.7-4.1.9-7.6-1.3-8.7-5.1-.3-1.2-.4-2.6-.2-4.2z"/><path d="M12.5 18.7c.3-3.1 1.8-5.6 4.6-7.2"/></>
  ),
  lipid: (
    <><circle cx="9.2" cy="10" r="4.4"/><circle cx="15.6" cy="14.8" r="3.6"/></>
  ),
  sugar: (
    <><path d="M12 3.6 20 8v8l-8 4.4L4 16V8z"/><path d="M4 8l8 4.4L20 8M12 12.4v8"/></>
  ),
  thyroid: (
    <><path d="M12 8.4v6.2"/><path d="M12 9.2C10.6 7 8.5 6 6.7 6.6 4.6 7.2 4 9.5 4.8 11.8c.8 2.3 2.9 3.8 5 3.3 1.4-.3 2.2-1.6 2.2-3z"/><path d="M12 9.2c1.4-2.2 3.5-3.2 5.3-2.6 2.1.6 2.7 2.9 1.9 5.2-.8 2.3-2.9 3.8-5 3.3-1.4-.3-2.2-1.6-2.2-3z"/></>
  ),
  flask: (
    <><path d="M8.4 3.5h7.2M10 3.5v6.2l-3.9 7.6a2.2 2.2 0 0 0 2 3.2h7.8a2.2 2.2 0 0 0 2-3.2L14 9.7V3.5"/><path d="M7.6 14.6h8.8"/></>
  ),
  body: (
    <><circle cx="12" cy="3.9" r="1.8"/><path d="M7.8 7.7h8.4M8.7 10.2h6.6M9.5 12.7h5M9.1 15.2h5.8M10.1 17.7h3.8"/><ellipse cx="12" cy="20.8" rx="5.4" ry="1.4"/></>
  ),
} as const;

export type IconName = keyof typeof ICON_PATHS;

export const ICON_NAMES = Object.keys(ICON_PATHS) as IconName[];

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'name'> {
  name: IconName | (string & {});
  /** Marks are decorative beside their own label; give a title only when alone. */
  title?: string;
}

/**
 * One component for every mark.
 *
 * Stroke width, colour and size come from CSS — the demo's rules target
 * `.side nav button svg`, `.tabbar button svg` and so on, and a component that
 * hard-coded them would win those cascades and quietly resize every mark.
 * An unknown name falls back to `home`, exactly as `HV.ui.icon` does, so a typo
 * is a wrong picture rather than a blank hole in the layout.
 */
export function Icon({ name, title, className, ...rest }: IconProps) {
  const paths = ICON_PATHS[name as IconName] ?? ICON_PATHS.home;
  return (
    <svg
      viewBox="0 0 24 24"
      /* hv-icon carries the hairline language at ZERO specificity, so every
         context rule app.css already writes still wins */
      className={className ? `hv-icon ${className}` : 'hv-icon'}
      aria-hidden={title ? undefined : true}
      role={title ? 'img' : undefined}
      focusable="false"
      {...rest}
    >
      {title ? <title>{title}</title> : null}
      {paths}
    </svg>
  );
}
